### ISSUE TITLE
Add description to meta tags

### ISSUE THREAD

**Issue by ClausWiingreen** [Beauty-by-Livia/website#1]
To improve SEO there should be a meta description tag

**Comment by Liviabcrw** [comment]
I organized the description for Google and the keywords, I believe it has become better.

**Comment by ClausWiingreen** [comment]
Okay, tried to insert into google to see how it would look: 
![image](https://github.com/user-attachments/assets/7d03c556-86b6-4664-8c01-985126b7742b)

**Comment by Liviabcrw** [comment]
PERFECT! I really really liked!
